### ISSUE TITLE
[Feature Request] Onboarding custom script actions

### ISSUE THREAD

**Issue by bennythehuman** [IBM/mac-ibm-notifications#136]
**Is your feature request related to a problem? Please describe.**
When onboarding it would be great to have a button that can execute a command, I would like to be able to offer richer onboarding workflows that are not just informational but also assist on getting a user set up for success

**Describe the solution you'd like**
The ability to create a button that executes a bash command, eg jamf policy -event eventName

**Describe alternatives you've considered**
Using HTML and adding in self service links which is a poor and messy experience

**Comment by SMartorelli** [comment]
Hi @bennythehuman the use case you suggest for a "Tertiary button" is not doable because in that case the app should have super user privileges to run command and IBM Notifier doesn't. 
While it is technically doable it requires the app to install a privileged helper on the user device that will work as satellite for the execution of privileged instructions and we do not plan to develop it.
We're already tracking another [FR](https://github.com/IBM/mac-ibm-notifications/issues/123) for the implementation of a customisable "Tertiary button" that could be placed on a page and provide the combined behaviour of the tertiary button and the info button on pop-up UI (open links or pop-over panels).

**Comment by SMartorelli** [comment]
Closing this issue since I didn't received any feedback from the reporter
