### ISSUE TITLE
[BUG] Option for font size, color and bold for a popup

### ISSUE THREAD

**Issue by mrmte** [IBM/mac-ibm-notifications#160]
Is there a way i can make the font size, color and bold for a popup -subtitle? I tried looking but could not see it.

Thanks

**Comment by SMartorelli** [comment]
Hi @mrmte I suggest you to use markdown attributes in the subtitle for simple stuff like bold, italic text (e.g. `"## This is markdown \n **It's cool**\n _It supports all major flavors_"`). Otherwise instead of a subtitle use an HTML accessory view where you can customise the text style as you wish. [Doc](https://github.com/IBM/mac-ibm-notifications/wiki/Pop-up-UI-Accessory-Views)

**Comment by mrmte** [comment]
i just tried /usr/local/bin/IBM\ Notifier.app/Contents/MacOS/IBM\ Notifier -accessory_view_type html -accessory_view_payload "<h1>Hello, world!</h1>this is a line of text<br><br><code>this is a code block<br>this is the second line of a code block</code><br>this is <span style="color: #ff0000">red</span> text"

it came back with sh: !: event not found

**Comment by SMartorelli** [comment]
Yes I'm sorry, I forgot that you need to escape the " inside the accessory view payload. It would be then `-accessory_view_type html -accessory_view_payload "<h1>Hello, world</h1>this is a line of text<br><br><code>this is a code block<br>this is the second line of a code block</code><br>this is <span style=\"color: #ff0000\">red</span> text" `

**Comment by mrmte** [comment]
Thanks very much for your help :)
