### ISSUE TITLE
[Feature Request] GIF Images not playing in Sonoma

### ISSUE THREAD

**Issue by marcusheBG** [IBM/mac-ibm-notifications#165]
**Describe the bug**
Just a heads up it seems that .gif images to do not play in popup windows in macOS 14.0 Sonoma Beta 1. Only the first frame of the .gif statically shows. Thanks so much!

**To Reproduce**
Attempting to display a .gif file in an image accessory view type popup when running on 10.14 macOS Sonoma beta 1

**Expected behavior**
For the .gif image to play and autoloop

**Desktop (please complete the following information):**
 - OS: macOS 14 Sonoma Beta 1
 - v-2.9.1-b-96

**Comment by SMartorelli** [comment]
Hi @marcusheBG 👋 actually IBM Notifier never officially supported GIF. I'm going to change this [BUG] to a [Feature Request] and start tracking it for v3.1.0 that should be released before the Sonoma public release 👍

**Comment by SMartorelli** [comment]
Thanks for confirming! Ok so version 3.0.0 that should be released this month will not support GIF since the migration to SwiftUI made it not "automatically" supported by the framework. We're working to enable the GIF support again in version 3.1.0 for all the supported macOSs. If GIFs are important to you/your org be aware of it when considering to update to the next release (3.0.0)
