### ISSUE TITLE
[BUG] Lack of spacing between icon and text in the popup UI

### ISSUE THREAD

**Issue by kryptonit1** [IBM/mac-ibm-notifications#194]
**Describe the bug**
The spacing between the icon and the text in the popup UI does not look good in 3.0.3 vs 2.9.1

**To Reproduce**
Launch the popup UI with a title and a subtitle in both version 2.9.1 and 3.0.3 and compare.

**Expected behavior**
The spacing to the right of the icon in the popup UI should be the same as the spacing to the left of the icon (just as in version 2.9.1) since this looks better and more uniformly.

**Screenshots**
**2.9.1**
![2 9 1](https://github.com/IBM/mac-ibm-notifications/assets/33235315/28767d2e-e24e-4f2a-b1ae-466045571145)
**3.0.3**
![3 0 3](https://github.com/IBM/mac-ibm-notifications/assets/33235315/fa8efe1a-741e-45ec-8b60-f59a064e3abd)

**Desktop (please complete the following information):**
 - OS: macOS 14
 - Project version: 3.0.3

**Comment by SMartorelli** [comment]
Hi @kryptonit1, thank you for the report. The new spacing between the icon and the body of the pop-up UI was actually made intentionally to better align with the old Apple HIG for Alerts (the old alert component for macOS represented in IBM Notifier by the popup UI). I can't provide a direct link to the old HIG since they're no longer available, but as you can see from the image below, the leading space for the icon was larger than the trailing space, just as in the new popup UI in IBM Notifier 3.0.3.
![alert_accessory_2x_ecd10446-574b-42e4-bf47-778220c9a52b](https://github.com/IBM/mac-ibm-notifications/assets/23209655/bf48d47a-40b3-414a-8abc-2e38656e004c)


This will also provide more space for the content of the dialog.
