### ISSUE TITLE
Onboarding - Text changes to left alignment when it wraps

### ISSUE THREAD

**Issue by tautest-tenures** [IBM/mac-ibm-notifications#204]
**Describe the bug**
Starting with v 3.x the onboarding window changes the text alignment for body to left justified when the text wraps to a new line.  I believe this may be a regression since v2.9.1 works as expected.

**To Reproduce**
1. Start onboarding UI with a page that has enough text in the body to wrap to a second line.
2. The text alignment changes from center to left justification.
3. See screenshot

**Expected behavior**
The text should remain centered when it wraps to the next line.

**Screenshots**
Onboarding with v3.x
![Image 1-24-24 at 10 30 AM](https://github.com/IBM/mac-ibm-notifications/assets/127993095/26abc2b9-6cec-462b-9057-4dd02313b04f)

Onboarding with v2.9.1
![Image 1-24-24 at 10 29 AM](https://github.com/IBM/mac-ibm-notifications/assets/127993095/12e4df1f-e7ef-4ae3-aa03-02472baa0506)

**Desktop (please complete the following information):**
 - OS: macOS 14.1
 - Project version: 3.0.0 - 3.1.0

**Additional context**
I tested each of the 3.x builds and encountered this behavior. v2.9.1 seems to work fine. I checked around and I didn't see documentation that this was new expected behavior.

**Comment by SMartorelli** [comment]
Hi @tautest-tenures, thank you for the report. Since the introduction of SwiftUI in IBM Notifier version 3.0.0, we have switched from a center-aligned body to a leading-aligned body in the onboarding UI. The good news is that if you prefer it to be centered, you just need to append your "body" text to your "subtitle". For example: `"subtitle": "Welcome to your Mac.\n\nLorem ipsum dolor sit amet, consectetur ...."`.

Regarding your attached screenshots, I think the left-right margin for the text in the new UI is a bit small. I'll create an issue to track this. In the meantime, if you, like me, are not fond of the new margins, you can use `\n` in your text to decide where a new line should start. It's not the prettiest solution, but it's effective!

**Comment by SMartorelli** [comment]
#206

**Comment by tautest-tenures** [comment]
@SMartorelli, I appreciate the response, explanation and suggestions! I'll be sure to give your suggestions a try as it sounds like that will get me close to what I'm looking for.  Thanks again for this great tool!
